version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    open-pull-requests-limit: 25
    schedule:
      # Check for npm updates on Sundays
      interval: 'daily'
    # Raise pull requests for version updates
    # against the `develop` branch
    target-branch: 'develop'
    # Labels on pull requests for version updates only
    versioning-strategy: increase

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions' # See documentation for possible values
    directory: '/' # Location of package manifests
    open-pull-requests-limit: 25
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Lisbon'
      day: 'sunday'
      time: '20:00'
